# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import test_pb2 as test__pb2


class TestServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.test = channel.unary_unary(
        '/athena.TestService/test',
        request_serializer=test__pb2.TestRequest.SerializeToString,
        response_deserializer=test__pb2.TestResponse.FromString,
        )


class TestServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def test(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TestServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'test': grpc.unary_unary_rpc_method_handler(
          servicer.test,
          request_deserializer=test__pb2.TestRequest.FromString,
          response_serializer=test__pb2.TestResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'athena.TestService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
